version: '3.8'
services:
  dev-db:
    image: postgres:15.3-alpine
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest-realtor-api

  test-db:
    image: postgres:15.3-alpine
    ports:
      - 5435:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test-nest-realtor-api

volumes:
  postgres-data:
